### ISSUE TITLE
FILECOIN + TEXTILE = NFT #2

### ISSUE THREAD

**Issue by raquelic** [protocol/polygon-grants#2]
TRACK 2: FILECOIN + TEXTILE = NFT: The best use of the Filecoin~Poylgon Bridge to automate the storage of unstoppable NFT assets on Filecoin.
Examples include integrating Bridges into an existing NFT platform, projects or scaffolding that integrate Bridges into NFT workflows, migrating existing NFT assets to Filecoin via Bridges, etc. Almost any NFT-specific application that stores assets on Filecoin via Bridges.

**Comment by nirohgo** [comment]
Hi, is this still open? how does participation work?

**Comment by zanadaos1105** [comment]
Filecoin brings many of the best parts of the IPFS stack, including verifiable data, peer-to-peer (p2p) data exchange, de-duplication, and more. We can create a more secure data storage layer for applications and their users by connecting to Filecoin storage.

When using the bridge, your users, app, or smart contract will still reference and retrieve data over IPFS. Additionally, the raw data will be available in storage contracts created with miners on the Filecoin network. The metadata for that storage is reported back to the native network Polygon or Ethereum .as open and reusable building blocks.

**Comment by lksbrssr** [comment]
hey @codista - you can register and participate by signing up on https://www.polygongrantshackathon.com/!

**Comment by clairedora** [comment]
Hey @codista @zanadaos1105 you guys can check the guidelines to participate in this bounty [https://hidorahacks.medium.com/how-does-a-bounty-hunter-tackle-a-hackerlink-bounty-5d2dd33716ac](https://hidorahacks.medium.com/how-does-a-bounty-hunter-tackle-a-hackerlink-bounty-5d2dd33716ac)

**Comment by ZhangPeibin** [comment]
@lksbrssr
Hello, I would like to participate in this bounty!

Here is the project I am submitting:
https://github.com/ZhangPeibin/AvatarMetaverse

Idea Description
We want to provide avatar NFT authentication scheme for users of Metaverse。
Our solution is to use web3 wallet and textile's Identity solution combined with DID to bind the avatar nft .
All nfts are uploaded through nft.storage and registered on polygon, and the wallet and other data are saved through textile and DID.

Avatar MetaData:

😉 11 face shapes
👃🏼 11 noses
👄 11 mouths
👀 11 eyes
👁️ 11 eyebrows
🕶️ 10 glasses
💇‍♀️ 30 hairstyles
🎅🏼 10 beards
💋 10 facial details
💍 10 accessories

So There are 400 million styles！

1.More meta attributes add more personality
2. AI is automatically generated based on user descriptions

Let us show ourselves in Metaverse！

Github Repo Link
https://github.com/ZhangPeibin/AvatarMetaverse

Demo Video Link
https://www.avatarverse.me/

**Comment by Jorropo** [comment]
> We want to provide avatar NFT authentication scheme for users of Metaverse。

@ZhangPeibin your current description doesn't include any filecoin bridging aspect and wouldn't fit this track.

An example thing you could add to make this valid is use Filecoin~Polygon to ensure from the polygon network that files are stored longterm on filecoin (this would be a bit simple).

I belive a better idea **for this track** would be a smart contract using the bridge to store on filecoin with a "stored on filecoin seal" for your NFTs.

Looking forward to see your submission :)

**Comment by ZhangPeibin** [comment]
> > We want to provide avatar NFT authentication scheme for users of Metaverse。
> 
> @ZhangPeibin your current description doesn't include any filecoin bridging aspect and wouldn't fit this track.
> 
> An example thing you could add to make this valid is use Filecoin~Polygon to ensure from the polygon network that files are stored longterm on filecoin (this would be a bit simple).
> 
> I belive a better idea **for this track** would be a smart contract using the bridge to store on filecoin with a "stored on filecoin seal" for your NFTs.
> 
> Looking forward to see your submission :)

That's cool ! We have some plans here:
1:  The avatar is produced by combining up to 10 attributes, such as hair, eyes, face shape, etc. These will be deployed through a contract and finally combined into an avatar, and the source files of the avatar will be stored in Filecoin through the contract.

2: From the avatar identity to our social metauniverse, then the user can publish his life records, public plans, etc. in the space, then these data will also be directly stored on filecoin through the contract.
